### ISSUE TITLE
Multiple Threads are stuck at GenericObjectPool.claim(GenericObjectPool.java:91) 

### ISSUE THREAD

**Issue by rahulbhawsar** [bbottema/generic-object-pool#4]
I am using simple java mail to send email,  and observed that couple of times my program stuck, after checking the thread dump I found that multiple threads are stuck at below Stracktrace: 

```

Simple Java Mail async mail sender, executor 1 / thread 1" #86 prio=5 os_prio=0 cpu=4130.48ms elapsed=1948.25s tid=0x0000fff5d8142aa0 nid=0x139 waiting on condition  [0x0000ffed3718d000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.11/Native Method)
	- parking to wait for  <merged>(a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.11/LockSupport.java:211)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.11/AbstractQueuedSynchronizer.java:715)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.11/AbstractQueuedSynchronizer.java:938)
	at java.util.concurrent.locks.ReentrantLock$Sync.lock(java.base@17.0.11/ReentrantLock.java:153)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@17.0.11/ReentrantLock.java:322)
	at org.bbottema.genericobjectpool.GenericObjectPool.claim(GenericObjectPool.java:91)
	at org.bbottema.clusteredobjectpool.core.ResourcePool.claim(ResourcePool.java:44)
	at org.bbottema.clusteredobjectpool.core.ResourceClusters.claimResourceFromCluster(ResourceClusters.java:124)
	at org.simplejavamail.internal.batchsupport.BatchSupport.acquireTransport(BatchSupport.java:113)
	at org.simplejavamail.mailer.internal.util.TransportRunner.sendUsingConnectionPool(TransportRunner.java:84)
	at org.simplejavamail.mailer.internal.util.TransportRunner.runOnSessionTransport(TransportRunner.java:72)
	at org.simplejavamail.mailer.internal.util.TransportRunner.sendMessage(TransportRunner.java:48)
	at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:82)
	at org.simplejavamail.mailer.internal.AbstractProxyServerSyncingClosure.run(AbstractProxyServerSyncingClosure.java:56)
	at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:345)
	at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:331)
```

we are using 
Simple Java Mail 6.6.1 and 
Generic Object Pool : 1.0.5 
Is there any recent fix done in latest version 2.0.1 to fix these kind of issues ? 

thanks,

**Comment by rahulbhawsar** [comment]
i think this observation can be closed, as I have observed when multiple thread are fighting to get the connection from the object pool , however with the introduction of one more lock ( responsible for deallocation) I have not observed this.
